### ISSUE TITLE
Warehouse not working with bags

### ISSUE THREAD

**Issue by poppyofmercy** [mikepauer/Carbonite.Warehouse#14]
Hi! I have a problem since patch 8.3:
When I put mouse over an item in my bags, warehouse is not shown. But when I move that object to an action bar the addon works perfectly. I don't know if it is a configuration problem or a bug so I'll post 2 images to show it.

![Image 1](https://user-images.githubusercontent.com/60145371/72819401-7cbbb680-3c6d-11ea-92e9-9cbdb06d7833.jpg)
![Image 2](https://user-images.githubusercontent.com/60145371/72819402-7cbbb680-3c6d-11ea-9a6b-7e433fb347fe.jpg)

**Comment by Rawan593** [comment]
I'm having exact same issue for the longest time!

**_Warehouse tooltip not showing when hovering over items in bags.
Warehouse tooltip is only showing when hovered over item on action bar._**

I hope this gets fixed soon. Please share any suggestions for a quick fix!

**Comment by IrcDirk** [comment]
Works in my 8.3 with no problems. Please disable all other addons leave only Carbonite + Modules enabled and check again. It might be incompatibility with other addon.

**Comment by Rawan593** [comment]
Thanks for the quick response!

I disabled all addons and only left Carbonite Maps + Carbonite Warehouse enabled.

Unfortunately, I'm still having the same issue.
Please see following screenshots.

![WoWScrnShot_061520_224602](https://user-images.githubusercontent.com/66970322/84699611-7dc1ed00-af5a-11ea-893e-7a0796e7efd1.jpg)
![WoWScrnShot_061520_224556](https://user-images.githubusercontent.com/66970322/84699616-7ef31a00-af5a-11ea-8c76-788b11cd0b91.jpg)

**Comment by IrcDirk** [comment]
Cant reproduce, works for me with any bag:

![obraz](https://user-images.githubusercontent.com/1030023/84739955-d28e5380-afac-11ea-97b7-94f9bad68c39.png)

![obraz](https://user-images.githubusercontent.com/1030023/84739948-cdc99f80-afac-11ea-8620-8943c70a77ec.png)

**Comment by IrcDirk** [comment]
All other items dont show tooltip with warehouse?

**Comment by Rawan593** [comment]
All other items don't show tooltip with warehouse.
Items that can be placed on an actionbar, do show the warehouse tooltip.

**Comment by IrcDirk** [comment]
Weird... the problem is that i cant reproduce this problem :(

**Comment by IrcDirk** [comment]
I see on your screen that u are using latest Release... try on latest Alpha => https://www.curseforge.com/wow/addons/carbonite/files/2957301

**Comment by IrcDirk** [comment]
U should update to Alpha releases, both Carbonite and Modules. There is option for this on Twitch/Curse client.

**Comment by Rawan593** [comment]
> U should update to Alpha releases, both Carbonite and Modules. There is option for this on Twitch/Curse client.

This worked! 🎉 Thanks so much, I really appreciate it! 😄❤️

**Comment by IrcDirk** [comment]
Ok so i need to make new live release 😉👍
