### ISSUE TITLE
nxwarehouse.lua line 843 setauctionitem is not a function error

### ISSUE THREAD

**Issue by clockworkmcd** [mikepauer/Carbonite.Warehouse#15]
getting the following error at startup with 8.3.0.1 carbonite.warehouse:

Date: 2020-02-24 11:28:38
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Warehouse\NxWarehouse.lua line 843:
   hooksecurefunc(): SetAuctionItem is not a function
Debug:
   [string "=[C]"]: hooksecurefunc()
   [string "@Carbonite.Warehouse\NxWarehouse.lua"]:843: func()
   [string "@DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua"]:57:
      ...\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:50

**Comment by IrcDirk** [comment]
Already fixed in aplha release. Use version from this repository or use Alpha release in Twitch client.
