### ISSUE TITLE
LUA Error on Open of Professions Window (Leatherworking)

### ISSUE THREAD

**Issue by amethystnw** [mikepauer/Carbonite.Warehouse#16]
Error occurs when opening a Professions Window.  Bug report as follows: 

5x Carbonite.Warehouse/NxWarehouse.lua:3490: attempt to call field 'GetTradeSkillLine' (a nil value)
[string "@Carbonite.Warehouse/NxWarehouse.lua"]:3490: in function `func'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
self = <table> {
 OnButToggleWarehouse = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:3514
 AddBag = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:2966
 OnLoot_opened = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:3226
 CaptureGet = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:3305
 OnUnit_spellcast_succeeded = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1125
 OnItem_lock_changed = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:2831
 UpdateItem = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:2239
 CaptureItems = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:2895
 ToggleShow = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1445
 OnGuildbankframe_closed = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:2737
 ImportDo = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1385
 AddLink = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:2984
 Menu_OnRemoveChar = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1348
 Menu_OnShowItemCat = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1414
 UpdateBlank = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1920
 Menu_OnSortByRarity = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1419
 OnTime_played_msg = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1102
 TooltipProcess = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:2646
 Menu_OnSortBySlot = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1428
 Menu_OnSyncAccount = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1407
 DurTooltipFrm = NxTooltipD {
 }
 OnChat_msg_skill = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:3318
 OnBankframe_closed = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:2719
 RecordCharacter = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:3547
 ReftipProcess = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:2607
 ExportDo = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1400
 LootItems = <table> {
 }
 Menu_OnExport = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1395
 FindCharsWithItem = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:2340
 ScanRBank = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:2957
 OnLoot_slot_cleared = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:3243
 OnItemListEvent = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1556
 OnUnit_inventory_changed = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:3006
 InitWarehouseCharacter = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:3518
 ConvertData = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:900
 UpdateGuild = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1927
 prtdb = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1216
 OnEditBox = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1465
 CaptureUpdate = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:2882
 CaptureInvDurabilityTimer = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:3166
 UpdateItems = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1992
 UpdateProfessions = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:2490
 OnListEvent = <function> defined @Carbonite.Warehouse/NxWarehouse.lua:1476
 OnTrade_skill_update = <function> defined @

**Comment by IrcDirk** [comment]
Fixed. Let me know if it works.

**Comment by amethystnw** [comment]
Your fix worked.  I get no errors opening any profession window.  All other addons running as well so no other conflicts noted.
