### ISSUE TITLE
Profession recipes/designs not showing in warehouse when clicked

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite.Warehouse#5]
Hi.

Going in to Carbonite Warehouse, open a character, clicking on a professions said character has, in this case my rogue and her engineering, nothing shows up.
![image](https://user-images.githubusercontent.com/31900265/33789153-f9d1c672-dc76-11e7-9c58-4a86609ca12f.png)

Being on a different toon or same toon checking a different toon and opening their respective profession in warehouse still leave the chosen profession empty.
![image](https://user-images.githubusercontent.com/31900265/33789220-55e2481a-dc77-11e7-8247-4b6312f59c55.png)

I was looking for some place to update it within carbonite or carbonite warehouse, but can't find anything so am guessing it's not there.

(Sorry, I know I asked 15 months ago on wowinterface.com on username Swirrel, but I was just thinking if making warehouse work for/in professions, is in any future plans?)

Thank you.
//Jag.

**Comment by mikepauer** [comment]
Fixed, opening a tradeskill window will now update warehouse with the info.

**Comment by Swirrel** [comment]
Sweet.
It's working like a charm

Thank you.
