### ISSUE TITLE
Just a few Questions :)

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite.Warehouse#8]
Hi.

Is Warehouse updated for Battle for Azeroth?

If it is, are there any significant changes to it that there haven't been previously? (e.g. like Legion, WoD, MoP ect.)
Could you link the update link for it, in your post? (I continously can't find it on this site) hehe.

Thank you in advance.

//Jag.

**Comment by IrcDirk** [comment]
Yes its updated, no changes since Legion only toc file.

https://www.curseforge.com/wow/addons/carbonite-warehouse

**Comment by Swirrel** [comment]
Awesome.

Thank you for the help :)
