### ISSUE TITLE
Installed Warehouse tonight, giving below error

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite.Warehouse#9]
9x Carbonite.Warehouse\NxWarehouse.lua:1968: attempt to index field '?' (a nil value)
Carbonite.Warehouse\NxWarehouse.lua:1968: in function `UpdateGuild'
Carbonite.Warehouse\NxWarehouse.lua:1912: in function `Update'
Carbonite.Warehouse\NxWarehouse.lua:2887: in function `func'
Carbonite\Libs\AceTimer-3.0\AceTimer-3.0-17.lua:57: in function <Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
self = <table> {
 OnButToggleWarehouse = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:3514
 AddBag = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:2966
 OnLoot_opened = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:3226
 NXEqRarityMin = 7
 CaptureGet = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:3305
 OnUnit_spellcast_succeeded = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1125
 OnItem_lock_changed = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:2831
 UpdateItem = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:2239
 CaptureItems = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:2895
 BankOpen = false
 ToggleShow = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1445
 OnGuildbankframe_closed = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:2737
 ImportDo = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1385
 AddLink = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:2984
 Menu_OnRemoveChar = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1348
 Menu_OnShowItemCat = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1414
 UpdateBlank = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1920
 Menu_OnSortByRarity = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1419
 SelectedChar = false
 OnTime_played_msg = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1102
 TooltipProcess = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:2646
 Menu_OnSortBySlot = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1428
 Menu_OnSyncAccount = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1407
 DurTooltipFrm = NxTooltipD {
 }
 OnChat_msg_skill = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:3318
 OnBankframe_closed = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:2719
 RecordCharacter = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:3547
 ReftipProcess = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:2607
 ExportDo = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1400
 Win = <table> {
 }
 Menu_OnExport = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1395
 FindCharsWithItem = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:2340
 ScanRBank = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:2957
 OnLoot_slot_cleared = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:3243
 SortByRarity = false
 OnItemListEvent = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1556
 SortBySlot = false
 OnUnit_inventory_changed = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:3006
 InitWarehouseCharacter = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:3518
 ConvertData = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:900
 OnLoot_closed = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:3261
 UpdateGuild = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1927
 SelectedGuild = "Old World"
 OnListEvent = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1476
 Menu = <table> {
 }
 EditBox = <table> {
 }
 prtdb = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1216
 ItemList = <table> {
 }
 OnEditBox = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:1465
 CaptureUpdate = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:2882
 List = <table> {
 }
 CaptureInvDurabilityTimer = <function> defined @I

**Comment by Swirrel** [comment]
That error came from my 2nd bank toon. Going to my 1st bank toon I realised what's giving the error...
I have the Carbonite minimap icon turned on. Right clicking the Carbonite minimap icon and mousing over and selecting Warehouse throws the error as you have to click Warehouse a second time for Warehouse to actually open up.
I don't recall to have encountered this odd behavior before from Warehouse.

Other than that it works great.

Thank you :)

**Comment by Swirrel** [comment]
Depositing items in to the Guild Bank and Personal Bank throws the same error. Same goes for if you withdraw from either Bank too.

Truth be told, I just needed a simple addon that could sell greys for me when visiting a vendor as the Elvui Team have F..... up their new version with a frame in the middle of screen showing me how many items are being sold and there is no way to turn that frame of as it's not implemented.
So technically I don't need ALL of Warehouse. Only a teeny tiny part of it.

**Comment by IrcDirk** [comment]
Fixed.

**Comment by Swirrel** [comment]
Idd it is.
Thank you very much :)
